### ISSUE TITLE
[Question]: What is the difference between mars and Ray?

### ISSUE THREAD

**Issue by dclong** [mars-project/mars#1206]
It seems to me that mars and Ray share something in common.

**Comment by qinxuye** [comment]
To my knowledge, Ray has not been donated to Apache Foundation. Thus just modify the title?

**Comment by qinxuye** [comment]
Ray focuses more on distributed runtime as well as machine learning tools, in contrast, Mars also offers a distributed runtime, but focuses more on data science technique stack. 

However, a great new is that, Ray and Mars can live together, they are not mutually exclusive. Now Mars on Ray is available since Mars v0.6.0a1. Refer to #1508 for more info.
