### ISSUE TITLE
Could you provide some common projects that use this framework?

### ISSUE THREAD

**Issue by poppingcode** [mars-project/mars#142]
I wanna try to use this framework

**Comment by chineking** [comment]
This is a brand new project, and users can apply Mars to their specified scenarios freely.

Since the community and projects grow, we may provide the projects which use Mars on our website then, please let we know when anyone finds Mars helpful, and also we need to build our website.

I can give a hint that currently Mars are applied to two inner projects, one uses Mars to do extremely huge tensor dot, the other takes advantage of the ability of Mars to do SVD decomposition on large tensors.

Mars cannot grow without the help from the entire community, and I wish you could join our community and give any feedback on Mars, this would be a great move.

**Comment by poppingcode** [comment]
OK，I will try to use it in the future. 
Do you know the official document address?

**Comment by chineking** [comment]
> Do you know the official document address?

Visit https://mars-project.readthedocs.io, choose language on the bottom left part, unfortunately, simplified Chinese only support the docs about distributed part of Mars.

**Comment by poppingcode** [comment]
ok ，thanks

**Comment by chineking** [comment]
I will close this issue first, we sincerely hope the community can give us feedback, contribute to Mars to make it better.
