### ISSUE TITLE
[PROPOSAL] Mutable tensor abstraction to expose storage layer of Mars

### ISSUE THREAD

**Issue by qinxuye** [mars-project/mars#415]
Mars is an execution engine dedicated to perform massive tensor or dataframe computation. Sometimes, if users want to just partially or concurrently update or read data in tensor, it's not effective and intuitive enough.

Thus I propose an abstraction called mutable tensor, which is different from non-volatile tensor that the user can create a chunked mutable tensor, and read and write chunk data concurrently. At last, users can transform the mutable tensor to a vanilla tensor to perform upcoming computations.

The API designs are listed below.

# Create mutable tensor

Create a mutable tensor via `session.create`.

```python
import mars.tensor as mt
from mars.session import new_session

sess = new_session('http://***', id='exist_session_id')

# create a 1000x2000 mutable tensor wich chunk size 500 on each dimension
# other clients can ref the same mutable tensor by the `name`
# compression and size of redundant can also be specified
a = mt.mutable_tensor(1000, 2000, chunk_size=500, name='mutable_tensor1',
                      compression='lz4', n_redundant=2)
sess.create(a)
```

# Get mutable tensor

Like I said, other clients can get the mutable tensor by its name.

```python
from mars.session import new_session

sess = new_session('http://***', id='exist_session_id')

a = sess.get('mutable_tensor1')
```

# Delete mutable tensor

```python
from mars.session import new_session

sess = new_session('http://***', id='exist_session_id')

sess.delete('mutable_session')
```

# Alias mutable tensor with another name

```python
from mars.session import new_session

sess = new_session('http://***', id='exist_session_id')
sess.alias(a, 'mutable_tensor2')
sess.get('mutable_tensor2')
```

# Write chunk data into mutable tensor

Write data by slice which is quite intuitive. At first, we can support write into only one chunk data with exact the chunk size, but we can support other situations later.

```python
import numpy as np

a[500:1000, :500] = np.empty(500, 500)
```

Other situations include fancy indexing way.

```python
import numpy as np

a[[0, 1, 2, 3], [4, 5, 6, 7]] = np.asarray([8, 9, 10, 11])
```

# Read chunk data

Still we can only support the exact range of the chunk at first. User can get a numpy ndarray here.

```python
array = a[500:1000, :500]
```

Fancy indexing can also be considered.

```python
import numpy as np

array2 = a[[0, 1, 2, 3], [4, 5, 6, 7]]
```

# Transform mutable tensor into vanilla tensor

Transform can be done via `session.seal`.

```python
from mars.session import new_session

sess = new_session('http://***', id='exist_session_id')

t = sess.seal(a)
# perform vanilla tensor computation
t.sum(axis=1).execute()
```

**Comment by chineking** [comment]
I think in order to implement mutable tensor, we need to do a few things.

1. We need a `MutableTensorActor`, when a user create a mutable tensor, a `MutableTensorActor` will be created by `SessionActor`, we need a `mars.tensor.core.MutableTensorData` as well, which could inherit from `mars.tensor.core.TensorData`, but with more properties like `name`, `n_redundant`, and `compression`.
2. `MarsAPI`, `MarsWebAPI` or `MarsWeb` could add more interfaces for mutable tensor. 
    *  `create_mutable_tensor(shape: tuple, chunk_size: any, name: str, compression: str, n_redundant: int)`, this API will create a `MutableTensorActor`.
    * `get_workers_storage_size() -> dict`, get all workers' storage size.
    * `set_chunk_worker_addresses(chunk_index: tuple, addresses: list) -> None`,  set worker addresses written to for a chunk.
    * `get_chunk_worker_addresses(chunk index: tuple) -> list`, get worker addresses a chunk allocated.
    * `write_chunk(chunk_index: tuple, data: bytes, worker_address: str)`, write chunk data to a worker.
    * `read_chunk(chunk_index: tuple, worker_address: str)  -> bytes`, read chunk data from a worker.
    * `write_slice_array(slices: tuple[slice], array: numpy.ndarray) -> dict`, write a ndarray into slices on each dimension, return a dict which key is the chunk_index and value is the worker address. Internally, the slice could be within or without a chunk, the function could handle it correctly.
    * `read_slice_array(slices: tuple[slice]) -> numpy.ndarray`, read a ndarray according to slices on each dimension. The slices could be across a few chunks, this function could handle it correctly.
    * `write_index_array(index_array: numpy.ndarray, data_array: numpy.ndarray) -> dict`, write a ndarray as a fancy indexing way, return a dict which key is the chunk_index and value is the worker address. Internally, the `index_array` could be involved in a few chunks, the function could handle it rightly.
   * `read_index_array(index_array: numpy.ndarray) -> numpy.ndarray`, read a ndarray according to fancy indexes on each axis. The fancy indexes could be across a few chunks, this function could handle it correctly.
3. `session` should add a few methods just mentioned in the proposal.

About the implementation, there is a key point is that, a chunk could be written for a few times, thus how to handle it is important, I think there are mainly two solutions.

1. We just store the data passed by user directly to shared memory, if shared memory not sufficient, the spill will be triggered automatically, when `seal` triggered, we will then merge them into one ndarray. 
2. We create a numpy ndarray on some process of a worker, the coming data could be updated on the ndarray. The advantage is that if the data is updated frequently, it could work better. The downside is that we cannot leverage the spill mechanism, if the memories are not sufficient, new chunk data could not be allocated any more.

We can discuss later when we come to this part.

cc @sighingnow if you have any question about the whole process. cc @wjsi if you have any further suggestion.

**Comment by sighingnow** [comment]
Now we have (almost) done the proposal, see [pr-464 comment](https://github.com/mars-project/mars/pull/464#issuecomment-503495484) for a runnable demo.

**Comment by sighingnow** [comment]
Close as in favour of #2195.
