### ISSUE TITLE
Worker should provide a way to read or write a chunk data

### ISSUE THREAD

**Issue by qinxuye** [mars-project/mars#450]
**Is your feature request related to a problem? Please describe.**

Worker should provide a way to read or write a chunk data, it would be helpful for web or scheduler if a numpy ndarray needs to be written into a worker.

**Describe the solution you'd like**

I thought we can leverage `ReceiverActor`, but it could be non-trivial. We can explore a better way if needed.

**Additional context**

This is important for implementation of mutable tensor.

**Comment by chineking** [comment]
@wjsi could give some suggestion.

cc @sighingnow if you have any further question.

**Comment by sighingnow** [comment]
I have some thoughts on this task: we provide two ways to read/write mutable arrays.

1. write/read mutable tensors from client to workers directly:

   + we provide something like `prepare_chunks`, which accept a series of indices as arguments, return a mapping of sub-indices, and keys and worker address of the corresponding sub-index.
   + users (or clients) are responsible for writing directly to workers with correct parts of data (can be indexed from whole data with sub-index). 

1. manipulate mutable tensors via scheduler:

    + users could write the data to the scheduler, and the scheduler could do some *optimization*, for example, shuffle or sort, then distribute those data to workers by chunk.
    + for example, when users do something like `tensor[1,11,4,3,7,9] = [1,2,3,4,5,6]`, we could benefits from pre-shuffle.
 
In this way, we don't need to shift some complex logic to the client and thus we don't need a heavy client to provide a functionality completeness and performance guarantee.

**Comment by chineking** [comment]
> I have some thoughts on this task: we provide two ways to read/write mutable arrays.
> 
> 1. write/read mutable tensors from client to workers directly:
>    
>    * we provide something like `prepare_chunks`, which accept a series of indices as arguments, return a mapping of sub-indices, and keys and worker address of the corresponding sub-index.

Yeah, just a dict is fine, {chunk index -> [workers]}

>    * users (or clients) are responsible for writing directly to workers with correct parts of data (can be indexed from whole data with sub-index).

The client can be in charge of calculating which chunks the data has effect on. For instance, I want to write data with fancy index: `a[[0, 0, 0], [1, 11, 15]] = [1, 2, 3]`

Assume the `chunk_size` on axis 1 is 10. so the data will be 2 parts: `[[0, 1, 1]] ` and `[[0, 1, 2], [0, 5, 3]]`, the data can be serialized and compressed and written to worker directly, or written to web and redirect to worker. On the worker side, the worker can just store the data into plasma. On the scheduler side, the scheduler can record a dict {chunk index -> [chunk sub keys]}.

If another client write data with another fancy index: `a[[0], [13]] = [4]`, `[[0, 3, 4]]` will be sent to the worker, and scheduler will know for a chunk, there are two pieces of data written for this chunk.

When seal triggered, we can do something like:

```
seal_data = np.zeros((10, 10))
data1 = np.asarray([[0, 1, 2], [0, 5, 3]])
data2 = np.asarray([[0, 1, 2], [0, 5, 3]])
seal_data[tuple(data1[:, :-1])] = data1[:, -1]
seal_data[tuple(data2[:, :-1])] = data2[:, -1]
``` 

> 2. manipulate mutable tensors via scheduler:
>    
>    * users could write the data to the scheduler, and the scheduler could do some _optimization_, for example, shuffle or sort, then distribute those data to workers by chunk.
>    * for example, when users do something like `tensor[1,11,4,3,7,9] = [1,2,3,4,5,6]`, we could benefites from pre-shuffle.

Could you give more benefits for optimization? But I don't think it's a good idea to handle data on the scheduler side.

> 
> In this way, we don't need to shift some complex logic to the client and thus we don't need a heavy client to provide a functionality completeness and performance guarantee.

I prefer to hand over the *heavy* part to client, because it's not suitable for either scheduler or web to do this part. Maybe web could do this, but I definitely disagree that scheduler is a good choice..
