### ISSUE TITLE
Simplify repeated reduction ops in a chain into one

### ISSUE THREAD

**Issue by wjsi** [mars-project/mars#532]
Tree reductions in Mars occasionally build operand chains like Reduction->Reduction for corners. This can be simplified by stopping creating reductions with one single inputs.

**Comment by qinxuye** [comment]
For the reduction op like `sum`, the map phase and combine phase is all sum op, so although the ops look the same, but actually they may have different properties.

Besides, for those reduction op like `mean`, the chunk ops would be different, maybe `MeanChunk` and `MeanCombine` etc.

Thus, I think it's by design, and won't fix it at least for now.
