### ISSUE TITLE
[Need to enhanced] It takes a long time to convert a tensor to a numpy ndarray.

### ISSUE THREAD

**Issue by sc1101** [mars-project/mars#955]
Hello, recently I found that it takes a long time to convert a tensor to a numpy ndarray. Especially a big one. The test code is as follows:

`import mars.tensor as mt`
`from mars.session import new_session`
`import numpy as np`
`import time`
`N = 5000`
`x = np.arange(N**2.).reshape(N, N)`
`y = np.arange(N**2.).reshape(N, N)`
`start = time.time()`
`x_t = mt.tensor(x)`
`y_t = mt.tensor(y)`
`z = mt.dot(x_t, y_t)`
`z = z.execute() # This line takes too  much time.`
`end = time.time()`
`print(z)`
`print("passTime: ", end - start)`

The code "z = z.execute()" convert a tensor z to a numpy ndarray, but it takes too much time.
My project needs to transfer the type between tensor and numpy ndarray frequently, so I want to ask  if it can be much faster to do that?

Thank you very much.

**Comment by qinxuye** [comment]
Mars is used to leverage multiple cores to accelerate Numpy tasks. It will try to split a huge ndarray into small ones, and generate fine-grained subtasks to perform the computation.

`execute` is used to trigger the process that I mentioned, and it will give back a numpy ndarray to user.

Mars will by default split a huge ndarray into few 128M bytes at most sized chunks.

For the task you mentioned, the input ndarrays are around 190M which is not very big, what's more, `dot` is one of few operations that numpy supported parallelism internally, most operations of numpy does not scale well on multi-core computers, but `dot` is an exception, thus Mars will not accelerate much for a single dot, maybe even slower because Mars does more things like splitting jobs etc other than computation itself.

Therefore, for the case you have shown, Mars would not be better than numpy itself.

However, you can try to accelerate with GPU.

```
x_t = mt.tensor(x).to_gpu().execute(fetch=False)
x_t.dot(x_t).execute()
```

You can try the code to see what will happen.

**Comment by qinxuye** [comment]
Besides, by running

```python
z.build_graph(tiled=True).view()
```

You can see how Mars generate the fined-grained tasks.

The picture is shown:

![dot](https://user-images.githubusercontent.com/357506/72915770-c72b5900-3d7b-11ea-883d-4b227be162c5.jpg)

**Comment by sc1101** [comment]
> Mars is used to leverage multiple cores to accelerate Numpy tasks. It will try to split a huge ndarray into small ones, and generate fine-grained subtasks to perform the computation.
> 
> `execute` is used to trigger the process that I mentioned, and it will give back a numpy ndarray to user.
> 
> Mars will by default split a huge ndarray into few 128M bytes at most sized chunks.
> 
> For the task you mentioned, the input ndarrays are around 190M which is not very big, what's more, `dot` is one of few operations that numpy supported parallelism internally, most operations of numpy does not scale well on multi-core computers, but `dot` is an exception, thus Mars will not accelerate much for a single dot, maybe even slower because Mars does more things like splitting jobs etc other than computation itself.
> 
> Therefore, for the case you have shown, Mars would not be better than numpy itself.
> 
> However, you can try to accelerate with GPU.
> 
> ```
> x_t = mt.tensor(x, gpu=True)
> x_t.execute(fetch=False)
> x_t.dot(x_t).execute()
> ```
> 
> You can try the code to see what will happen.

Hello! Thanks for your advice, I tried these code in "colaboratory" (because my computer still can't use GPU for mars), it is faster now although it converts a tensor to a numpy ndarray.
